name: Pull Request Tests

# This workflow runs comprehensive tests on pull requests to ensure
# code quality and prevent regressions. Uses unified test scripts
# for consistent testing across environments.

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'third_party/**'
      - 'scripts/**'
      - 'CMakeLists.txt'
      - '.github/workflows/pr-tests.yml'
  
  # Allow manual triggering for testing workflow changes
  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-latest
    timeout-minutes: 35
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup dependencies
      run: |
        # Install required tools
        brew install cmake googletest
        
        # Verify tools are available
        cmake --version
        
    - name: Initial project setup
      run: |
        # Use our unified build script for setup
        ./scripts/build.sh setup
    
    - name: Build project
      run: |
        # Use our unified build script for building
        ./scripts/build.sh debug --quiet
    
    - name: Run all tests
      run: |
        # Use our unified test script
        ./scripts/test.sh --quiet
    
    - name: Run specific test categories
      run: |
        echo "=== Unit Tests ==="
        ./scripts/test.sh --unit --quiet
        
        echo "=== Integration Tests ==="
        ./scripts/test.sh --integration --quiet
        
        echo "=== Regression Tests ==="
        ./scripts/test.sh --regression --quiet
    
    - name: Validate Audio Unit
      run: |
        # Use our unified test script for Audio Unit validation
        ./scripts/test.sh --auval
      continue-on-error: true  # Don't fail the workflow if auval has issues
    
    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.run_number }}
        path: |
          build/Testing/
          build/auval_output.txt
          build/bin/YMulatorSynthAU_Tests
        retention-days: 7
        
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ github.run_number }}
        path: |
          build/*.log
          build/CMakeFiles/CMakeOutput.log
          build/CMakeFiles/CMakeError.log
        retention-days: 3